AllCops:
  TargetRubyVersion: 2.6
  SuggestExtensions: false
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
  Exclude:
    - lib/miro/downsampler/histogram.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*